language: python
sudo: true

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install -U pip
  - pip install --no-binary pycparser
  - pip install psycopg2
  - pip install sqlalchemy
  - pip install flake8
  - pip install coverage
  - pip install nose
  - pip install coveralls
  - python setup.py develop

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres

script:
  - flake8 anyblok
  - psql -c 'create database travis_ci_test;' -U postgres
  - nosetests anyblok_rea/tests -v -s --with-coverage --cover-package=anyblok_rea
  - psql -c 'drop database travis_ci_test;' -U postgres
  - anyblok_createdb --install-all-bloks
  - nosetests anyblok_rea --with-anyblok-bloks -v -s --with-coverage --cover-package=anyblok_rea
  
after_success:
  coveralls
